title: Baked Goods Classifier
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>  
